services:
  wm-bot:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: iamthekidyouknow/wm-dc-app:latest
    container_name: wm-bot-c
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}

  mongo-db:
    image: mongo:latest
    container_name: mongodb-c
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./volumes/mongodb/prod:/data/db

volumes:
  mongodb_data:
