services:
  wm-bot:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    image: iamthekidyouknow/wm-dc-app:latest
    container_name: wm-bot-c
    restart: unless-stopped
    env_file:
      - .env.dev
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongodb-c
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./volumes/mongodb/dev:/data/db

volumes:
  mongodb_data:
